import numpy as np
import MDAnalysis as mda
from MDAnalysis.lib.distances import distance_array
import matplotlib.pyplot as plt
import time
import math
import os

def generate_topology(traj_file, data_file):
    """
    Generate a LAMMPS data file from the first frame of the trajectory
    to provide topology (masses) information.
    """
    if os.path.exists(data_file):
        return

    print(f"Generating topology file: {data_file}")
    
    with open(traj_file, 'r') as f:
        lines = f.readlines()
    
    # Parse header info from first frame
    # ITEM: TIMESTEP
    # 0
    # ITEM: NUMBER OF ATOMS
    # 5541
    # ITEM: BOX BOUNDS pp pp pp
    # xlo xhi
    # ylo yhi
    # zlo zhi
    # ITEM: ATOMS id type x y z
    
    try:
        n_atoms_idx = lines.index("ITEM: NUMBER OF ATOMS\n") + 1
        n_atoms = int(lines[n_atoms_idx])
        
        box_idx = lines.index("ITEM: BOX BOUNDS pp pp pp\n") + 1
        xlo, xhi = map(float, lines[box_idx].split())
        ylo, yhi = map(float, lines[box_idx+1].split())
        zlo, zhi = map(float, lines[box_idx+2].split())
        
        atoms_start_idx = lines.index("ITEM: ATOMS id type xu yu zu\n") + 1
        
        with open(data_file, 'w') as f:
            f.write("Generated by simple_tetrahedral_analysis.py\n\n")
            f.write(f"{n_atoms} atoms\n")
            f.write("3 atom types\n\n")
            
            f.write(f"{xlo} {xhi} xlo xhi\n")
            f.write(f"{ylo} {yhi} ylo yhi\n")
            f.write(f"{zlo} {zhi} zlo zhi\n\n")
            
            f.write("Masses\n\n")
            f.write("1 12.011 # C\n")
            f.write("2 15.999 # O\n")
            f.write("3 1.008  # H\n\n")
            
            f.write("Atoms # atomic\n\n")
            
            for i in range(n_atoms):
                line = lines[atoms_start_idx + i]
                # dump: id type x y z
                # data atomic: id type x y z
                # Just copy the line is fine if order matches, but let's be safe
                parts = line.split()
                atom_id = parts[0]
                atom_type = parts[1]
                x, y, z = parts[2], parts[3], parts[4]
                f.write(f"{atom_id} {atom_type} {x} {y} {z}\n")
                
    except Exception as e:
        print(f"Error generating topology: {e}")
        # Create a dummy file if parsing fails to avoid crash, but likely will fail later
        pass

def calculate_tetrahedral_order(oxygen_coords, box):
    """
    Calculate Tetrahedral Order Parameter q for each water molecule using NumPy.
    q = 1 - 3/8 * sum_j sum_k (cos(psi_jk) + 1/3)^2
    """
    n_waters = len(oxygen_coords)
    q_values = np.zeros(n_waters)
    
    # Calculate all pairwise distances with PBC
    # distance_array returns distances, but we also need vectors for angles.
    # For simplicity in this demo, we'll use distance_array to find neighbors,
    # then manually compute vectors for the nearest 4.
    
    # Note: For very large systems, this N^2 approach is slow. 
    # KDTree or Cell Lists are better. But for ~2000 atoms, it's fine.
    dists = distance_array(oxygen_coords, oxygen_coords, box=box)
    
    # Set self-distance to infinity to ignore
    np.fill_diagonal(dists, np.inf)
    
    # Find 4 nearest neighbors for each atom
    # argsort along axis 1, take first 4
    nearest_indices = np.argsort(dists, axis=1)[:, :4]
    
    for i in range(n_waters):
        neighbors = nearest_indices[i]
        
        # Get vectors to neighbors applying PBC
        vecs = []
        norms = []
        
        pos_i = oxygen_coords[i]
        
        for idx_j in neighbors:
            pos_j = oxygen_coords[idx_j]
            
            # Vector i -> j
            delta = pos_j - pos_i
            
            # Apply PBC (Minimum Image Convention)
            delta -= box[:3] * np.round(delta / box[:3])
            
            norm = np.linalg.norm(delta)
            vecs.append(delta)
            norms.append(norm)
            
        # Compute q
        sum_term = 0.0
        count = 0
        
        for j in range(3):
            for k in range(j+1, 4):
                # Cosine of angle between vector j and vector k
                dot_prod = np.dot(vecs[j], vecs[k])
                cos_psi = dot_prod / (norms[j] * norms[k])
                
                term = cos_psi + 1.0/3.0
                sum_term += term * term
                count += 1
                
        q_values[i] = 1.0 - (3.0/8.0) * sum_term
        
    return q_values

def calculate_steinhardt_proxy(oxygen_coords, box, n_neighbors=12):
    """
    Compute simple proxy for Steinhardt order: variance of neighbor distances.
    Higher variance -> Less ordered (Liquid)
    Lower variance -> More ordered (Ice-like)
    We map this to a 0-1 scale using exp(-variance).
    """
    n_waters = len(oxygen_coords)
    
    # Calculate distances
    dists = distance_array(oxygen_coords, oxygen_coords, box=box)
    np.fill_diagonal(dists, np.inf)
    
    # Sort to find nearest neighbors
    sorted_dists = np.sort(dists, axis=1)
    
    # Take nearest N neighbors
    nearest_dists = sorted_dists[:, :n_neighbors]
    
    # Calculate variance of distances for each atom
    variances = np.var(nearest_dists, axis=1)
    
    # Proxy value
    q_proxy = np.exp(-variances)
    
    return q_proxy

def main():
    traj_file = "snippet.lammpstrj"
    topo_file = "system.data"
    
    print(f"Trajectory: {traj_file}")
    
    # Generate topology if needed
    generate_topology(traj_file, topo_file)
    
    try:
        # Load with topology and dt to fix warnings
        # dt=0.002 ps (2 fs)
        u = mda.Universe(topo_file, traj_file, format='LAMMPSDUMP', dt=0.002, atom_style='id type x y z')
        print(f"Loaded {len(u.trajectory)} frames, {len(u.atoms)} atoms")
    except Exception as e:
        print(f"Error loading trajectory: {e}")
        return

    # Select Water Oxygens
    oxygens = u.select_atoms('type 2')
    print(f"Number of water oxygens: {len(oxygens)}")

    if len(oxygens) == 0:
        print("No oxygen atoms found (type 2).")
        return

    # Storage for results
    times = []
    avg_q = []
    avg_steinhardt = []
    
    all_q_values = [] # For histogram

    print("Starting analysis (NumPy)...")
    start_time = time.time()

    for ts in u.trajectory:
        box = ts.dimensions
        coords = oxygens.positions
        
        # 1. Tetrahedral Order
        q_vals = calculate_tetrahedral_order(coords, box)
        mean_q = np.mean(q_vals)
        
        # 2. Steinhardt Proxy
        st_vals = calculate_steinhardt_proxy(coords, box)
        mean_st = np.mean(st_vals)
        
        times.append(ts.frame)
        avg_q.append(mean_q)
        avg_steinhardt.append(mean_st)
        all_q_values.extend(q_vals)
        
        print(f"Frame {ts.frame}: Mean Q = {mean_q:.4f}, Mean Steinhardt = {mean_st:.4f}")

    end_time = time.time()
    print(f"\nAnalysis complete in {end_time - start_time:.2f} seconds.")

    # =========================================================================
    # PLOTTING
    # =========================================================================
    print("Generating plots...")
    
    fig = plt.figure(figsize=(12, 10))
    gs = fig.add_gridspec(2, 2)
    
    # Plot 1: Tetrahedral Order vs Time
    ax1 = fig.add_subplot(gs[0, 0])
    ax1.plot(times, avg_q, 'b-o', label='Tetrahedral Order (q)')
    ax1.set_xlabel('Frame')
    ax1.set_ylabel('Average q')
    ax1.set_title('Tetrahedral Order Evolution')
    ax1.grid(True, alpha=0.3)
    ax1.legend()
    
    # Plot 2: Steinhardt Proxy vs Time
    ax2 = fig.add_subplot(gs[0, 1])
    ax2.plot(times, avg_steinhardt, 'r-s', label='Steinhardt Proxy')
    ax2.set_xlabel('Frame')
    ax2.set_ylabel('Proxy Value')
    ax2.set_title('Steinhardt Proxy Evolution')
    ax2.grid(True, alpha=0.3)
    ax2.legend()
    
    # Plot 3: Distribution of q (Histogram)
    ax3 = fig.add_subplot(gs[1, :])
    ax3.hist(all_q_values, bins=50, color='purple', alpha=0.7, edgecolor='black')
    ax3.set_xlabel('Tetrahedral Order Parameter (q)')
    ax3.set_ylabel('Count')
    ax3.set_title('Distribution of Tetrahedral Order Parameter')
    ax3.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('water_structure_analysis.png', dpi=300)
    print("Plot saved to 'water_structure_analysis.png'")

if __name__ == "__main__":
    main()
